### ISSUE TITLE
Redirect from shtml pages doesn't work

### ISSUE THREAD

**Issue by germanattanasio** [nfriedly/docpad-plugin-redirector#3]
#### Steps to reproduce:

1. Add redirect rule:

   ```
   '/folder1/page.shtml': '/folder2/page2.shtml'
   ```

#### Expected behaviour

`folder2/page.shtml` with the redirect header

#### Actual behaviour

A new file called `folder2/page.shtml/index.shtml`

**Comment by nfriedly** [comment]
Fixed in #4
